name: release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - '*'

  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
      tag:
        description: NPM tag
        default: beta
        required: true
      dry:
        description: Dry run
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

env:
  RELEASE_VERSION: ${{ github.event.inputs.version || github.ref_name }}
  RELEASE_TAG: ${{ github.event.inputs.tag || 'latest' }}

jobs:
  release:
    if: ${{ github.repository == 'mistic100/Photo-Sphere-Viewer' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: setup
        uses: ./.github/workflows/shared/setup
        with:
          turbo-cache: 'false'

      - name: build
        run: |
          pnpm ci:version ${{ env.RELEASE_VERSION }}
          pnpm ci:build

      - name: package
        if: ${{ github.ref_type == 'tag' }}
        run: |
          PREVIOUS_TAG=$(git tag --sort=-committerdate | sed -n '2 p')
          echo '📂 prepare'
          node ./build/prepare-package.mjs
          echo '📦 archive'
          (cd dist && zip -r photo-sphere-viewer-${{ github.ref_name }}.zip .)
          echo '📄 changelog'
          git log --pretty=format:"%s" $PREVIOUS_TAG...${{ github.ref_name }} | node ./build/generate-changelog.mjs $PREVIOUS_TAG ${{ github.ref_name }} > dist/changelog_${{ github.ref_name }}.md

      - name: create release
        if: ${{ github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          body_path: dist/changelog_${{ github.ref_name }}.md
          files: dist/photo-sphere-viewer-${{ github.ref_name }}.zip

      - name: npm publish
        run: |
          pnpm ci:publish ${{ github.event.inputs.dry && '-- --dry-run' || '' }}
        env:
          NPM_TAG: ${{ env.RELEASE_TAG }}

      - name: update issue templates
        if: ${{ github.ref_type == 'tag' }}
        run: |
          git fetch origin main --depth 1
          git checkout main
          node ./build/update-issue-templates.mjs ${{ github.ref_name }}
          git stage .github/ISSUE_TEMPLATE
          git config --global user.email "noreply@github.com"
          git config --global user.name "github-actions"
          git commit -m "chore: add ${{ github.ref_name }} to issue templates"
          git push
